### ISSUE TITLE
device.launchApp({newInstance: true}) doesn't start a new instance of the app

### ISSUE THREAD

**Issue by j320** [mathanpec/react-native-detox-cucumber#1]
When trying to relaunch the app as a new instance in the _Before_ hook with the line specified in the title, the app launches with the existing session as oppose to a new one as expected

**Comment by mmcconway** [comment]
Not a maintainer or anything, but currently trying this setup out 😄

Is this what you have so far @J320 ?

Inside support/init.js:
`Before(async (context) => {
  await detox.device.launchApp({newInstance: true})
  await adapter.beforeEach(context)
});`

Also would be good to know if this is an issue on ios or android

**Comment by mathanpec** [comment]
Hey @J320,

I just tried out `device.launchApp({newInstance: true})` in the before hook and it worked as expected. It launched a new session after every scenario. Can you pls share an example repo or something where we could reproduce that?

**Comment by j320** [comment]
Actually, I found that `await device.launchApp({delete:true})` does the job. In this case we can close the issue.
